version: '3'
services:
    mysql:
        image: mysql:8.0.11
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: JasonXK@D0cker
        volumes:
            - "./mysql/conf:/etc/mysql"
            - "./mysql/mysql:/var/lib/mysql"
        networks:
            app_net:
                ipv4_address: 10.10.10.1
        container_name: "compose-mysql"
    redis:
        image: redis:4.0.9
        ports:
            - "6379:6379"
        volumes:
            - "./redis:/var/redis"
        networks:
            app_net:
        restart: always
        command: redis-server --appendonly yes
        container_name: "compose-redis"
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - "php"
        volumes:
            - "./nginx/conf.d:/etc/nginx/conf.d"
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./logs/nginx:/var/log/nginx"
            - "./html:/var/www/html"
        links:
            - php
        networks:
            - app_net
        container_name: "compose-nginx"
    php:
        build: ./php
        ports:
            - "9000:9000"
        volumes:
            - "./php/conf/php.ini:/usr/local/etc/php/php.ini"
            - "./php/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf"
            - "./php/conf/php-fpm.d:/usr/local/etc/php-fpm.d"
            - "./html:/var/www/html"
        links:
            - mysql
            - redis
        networks:
            - app_net
        container_name: "compose-php"
networks:
    app_net:
        driver: bridge
        ipam:
            config:
                - subnet: 10.10.0.0/16

